[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
command = "cargo"
args = ["fmt"]
install_crate = "rustfmt"

[tasks.test]
command = "cargo"
args = ["test"]

[tasks.pre-commit]
dependencies = [
	"format",
	"test"
]
